### ISSUE TITLE
ClientException

### ISSUE THREAD

**Issue by guglielmo** [Apress/practical-docker-with-python#2]
Following the instructions, when fetching the news:
```
NBT_ACCESS_TOKEN=<token> python newsbot.py
```
within the `docker subreddit fetcher` directory, I receive the following error:
```
INFO: 2018-09-03 17:49:10,101 - post_message - posting Hang on, fetching your news.. to 25359320
Traceback (most recent call last):
  File "newsbot.py", line 24, in <module>
    handle_incoming_messages(States.last_updated)
  File "/Users/gu/Workspace/telegram_bots/practical-docker-with-python/docker subreddit fetcher/telegram.py", line 85, in handle_incoming_messages
    summarized_news = get_latest_news(sources_dict[person_id])
  File "/Users/gu/Workspace/telegram_bots/practical-docker-with-python/docker subreddit fetcher/reddit.py", line 14, in get_latest_news
    r = praw.Reddit(user_agent='Telegram Xiled Chippians Group')
  File "/Users/gu/Workspace/telegram_bots/practical-docker-with-python/venv/lib/python3.7/site-packages/praw/reddit.py", line 150, in __init__
    raise ClientException(required_message.format(attribute))
praw.exceptions.ClientException: Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.
```

Shouldn't the bot authenticate against the Reddit API?

**Comment by zoldaten** [comment]
```
#file reddit.py
#make app on reddit first to get keys

import praw
from states import log

#https://www.reddit.com/wiki/api
#https://www.reddit.com/prefs/apps
#https://stackoverflow.com/questions/39521621/raise-clientexceptionrequired-message-formatattribute-praw-exceptions-client

def get_latest_news(sub_reddits):
    log.debug('Fetching news from reddit')
    #r = praw.Reddit(user_agent='Practical Docker With Python tutorial')
    r = praw.Reddit(
        username="user_name_on_reddit",
        password="password_on_rediit",
        client_id="see stackoverflow at the beginning",
        client_secret="see stackoverflow at the beginning",
        user_agent="Karma breakdown 1.0 by /u/zoldaten_",
        redirect_uri='http://127.0.0.1:65010/',
    )
    
    sub_reddits = clean_up_subreddits(sub_reddits)
    log.debug(f"Fetching subreddits: {sub_reddits}")    
    submissions = r.subreddit(sub_reddits).top(limit=5)
    submission_content = ''
    try:
        for post in submissions:
            submission_content += f"{post.title} - {post.url} \n\n"
    except praw.errors.Forbidden:
            log.info(f"subreddit {sub_reddits} is private".format())
            submission_content = "Sorry couldn't fetch; subreddit is private"
    except praw.errors.InvalidSubreddit:
            log.info(f"Subreddit {sub_reddits} is invalid or doesn''t exist.")
            submission_content = "Sorry couldn't fetch; subreddit doesn't seem to exist"
    except praw.errors.NotFound :
            log.info(f"Subreddit {sub_reddits} is invalid or doesn''t exist.")
            submission_content = "Sorry couldn't fetch; something went wrong, please do send a report to @sathyabhat"
    return submission_content
    
def clean_up_subreddits(sub_reddits):
    log.debug('Got subreddits to clean: {0}'.format(sub_reddits))
    return sub_reddits.strip().replace(" ", "").replace(',', '+')
```
